#spring.application.name=review-micro-service
server:
  port: 8083


spring:
  application:
    name: review-micro-service
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: parjunb
    password: parjunb
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/