#spring.application.name=review-micro-service
server:
  port: 8083


spring:
  application:
    name: review-micro-service
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

